[project]
name = "vertex-ai-samples"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "google-cloud-aiplatform>=1.73.0",
    "ruff>=0.8.1",
    "sentencepiece>=0.2.0",
]
